var movie1 = { title: "Silence of the Lambs", description: "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.", genre: { name: "Thriller", description: "Thrillers expertly blend mystery, tension, and anticipation into one exciting story. Successful thrillers are well-paced, often introducing red herrings, divulging plot twists, and revealing information at the exact right moments to keep the audience intrigued. Thrillers often include a “ticking clock” aspect, where the stakes are against a finite amount of time. Crime films, political thrillers, and techno-thrillers are all featured in the thriller genre." }, director: {name: "Jonathan Demme", bio: "Robert Jonathan Demme was an American film and television director, producer and screenwriter whose career spanned over 30 years.", birth: new Date("1944-01-01"), death: new Date("2017-01-01") },actors: [{name: "Jodie Foster", bio: "Alicia Christian \"Jodie\" Foster is an American actress and filmmaker. She is the recipient of numerous accolades, including two Academy Awards, three BAFTA Awards, three Golden Globe Awards, and a Screen Actors Guild Award. For her work as a producer and director, she has been nominated for a Primetime Emmy Award.", birth: new Date("1962-11-19") },{ name: "Anthony Hopkins",bio: "Sir Philip Anthony Hopkins CBE is a Welsh actor, director, and producer. One of Britain's most recognisable and prolific actors, he is known for his performances on the screen and stage.", birth: new Date("1937-12-31") }], imagePath: "silenceofthelambs.png", featured: true}; db.movies.insertOne(movie1);
var movie1 = { title: "The Shawshank Redemption", description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Frank Darabont", bio: "Frank Árpád Darabont is a French-born American film director, screenwriter and producer. He has been nominated for three Academy Awards and a Golden Globe Award. In his early career, he was primarily a screenwriter for such horror films as A Nightmare on Elm Street 3: Dream Warriors, The Blob and The Fly II.", birth: new Date("1959-01-28") }, actors: [{name: "Robbins", bio: "Timothy Francis Robbins is an American actor, director and producer. He is best known for portraying Andy Dufresne in the film The Shawshank Redemption, and has won a Best Supporting Actor Academy Award and Golden Globe for his role in Mystic River and another Golden Globe as Best Actor for The Player.", birth: new Date("1958-10-16")},{name: "Morgan Freeman", bio: "Morgan Freeman is an American actor and producer. He is known for his distinctive deep voice and various roles in a wide variety of film genres. Throughout his career spanning over five decades, he has received numerous accolades, including an Academy Award, a Screen Actors Guild Award, and a Golden Globe Award.", birth: new Date("1937-06-01")}, { name: "Bob Gunton", bio: "Robert Patrick Gunton Jr. is an American character actor of stage and screen. He is known for playing strict authoritarian characters, including Warden Samuel Norton in the 1994 prison drama The Shawshank Redemption, Chief George Earle in 1993's Demolition Man, Dr. Walcott, the domineering dean of Virginia Medical School in Patch Adams, and Secretary of State Cyrus Vance in Argo. He also played Leland Owlsley in the Daredevil television series, Secretary of Defense Ethan Kanin in 24, and Noah Taylor in Desperate Housewives.",
birth: new Date("1945-11-15")}] , imagePath: "theshawshankredemption.png", featured: true}; db.movies.insertOne(movie1);
var movie1 = { title: "The Godfather", description: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Francis Ford Coppola", bio: "Francis Ford Coppola is an American film director, producer, and screenwriter. He is considered one of the major figures of the New Hollywood filmmaking movement of the 1960s and 1970s. Coppola is the recipient of five Academy Awards, six Golden Globe Awards, two Palmes d'Or and a British Academy Film Award.", birth: new Date("1939-04-07") }, actors: [{ name: "Marlon Brando", bio: "Marlon Brando Jr. was an American actor and activist. Considered one of the greatest actors of the 20th century, he received numerous accolades throughout his career, which spanned six decades, including two Academy Awards, two Golden Globe Awards, one Cannes Film Festival Award and three British Academy Film Awards.", birth: new Date("1924-04-03"), death: new Date("2004-07-01")},{ name: "Al Pacino", bio: "Alfredo James Pacino is an American actor. Considered one of the greatest and most influential actors of the 20th century, Pacino has received numerous accolades: including an Academy Award, two Tony Awards, and two Primetime Emmy Awards, making him one of the few performers to have achieved the Triple Crown of Acting. He has also been honored with the Cecil B. DeMille Award in 2001, the AFI Life Achievement Award in 2007, the National Medal of Arts in 2011, and the Kennedy Center Honors in 2016.", birth: new Date("1940-04-25")},{name: "James Caan", bio: "James Edmund Caan was an American actor. He came to prominence playing Sonny Corleone in The Godfather – a performance which earned him Academy Award and Golden Globe nominations for Best Supporting Actor. He reprised his role in The Godfather Part II.", 
birth: new Date("1940-03-26"), death: new Date("2022-07-06")}] , imagePath: "thegodfather.png", featured: true}; db.movies.insertOne(movie1);
var movie1 = { title: "The Dark Knight", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", genre: { name: "Action", description: "Movies in the action genre are fast-paced and include a lot of action like fight scenes, chase scenes, and slow-motion shots. They can feature superheroes, martial arts, or exciting stunts. These high-octane films are more about the execution of the plot rather than the plot itself. Action movies are thrilling to watch and leave audience members on the edge of their seats." }, director: {name: "Chrisopher Nolan", bio: "Christopher Edward Nolan CBE is a British and American filmmaker. Known for his Hollywood blockbusters with complex storytelling, Nolan is considered a leading filmmaker of the 21st century. His films have grossed $5 billion worldwide.", birth: new Date("1970-07-30") }, actors: [{name: "Christian Bale", bio: "Christian Charles Philip Bale is an English actor. Known for his versatility and physical transformations for his roles, he has been a leading man in films of several genres. He has received various accolades, including an Academy Award and two Golden Globe Awards.", birth: new Date("1974-01-30") },{ name: "Heath Ledger", bio: "Heath Andrew Ledger was an Australian actor. After playing roles in several Australian television and film productions during the 1990s, Ledger moved to the United States in 1998 to develop his film career further.", birth: new Date("1979-04-04"), death: new Date("2008-01-22") },{name: "Aaron Echart", bio: "Aaron Edward Eckhart is an American actor. Born in Cupertino, California, Eckhart moved to the United Kingdom at an early age. He began his acting career by performing in school plays, before moving to Australia for his high school senior year.", birth: new Date("1968-03-12")}] , imagePath: "thedarkknight.png", featured: true}; db.movies.insertOne(movie1);
var movie1 = { title: "The Godfather Part II", description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Francis Ford Coppola", bio: "Francis Ford Coppola is an American film director, producer, and screenwriter. He is considered one of the major figures of the New Hollywood filmmaking movement of the 1960s and 1970s. Coppola is the recipient of five Academy Awards, six Golden Globe Awards, two Palmes d'Or and a British Academy Film Award.", birth: new Date("1939-04-07") }, actors: [{ name: "Al Pacino", bio: "Alfredo James Pacino is an American actor. Considered one of the greatest and most influential actors of the 20th century, Pacino has received numerous accolades: including an Academy Award, two Tony Awards, and two Primetime Emmy Awards, making him one of the few performers to have achieved the Triple Crown of Acting. He has also been honored with the Cecil B. DeMille Award in 2001, the AFI Life Achievement Award in 2007, the National Medal of Arts in 2011, and the Kennedy Center Honors in 2016.", birth: new Date("1940-04-25")},{ name: "Robert De Niro", bio: "Robert Anthony De Niro is an American actor. Known for his collaborations with Martin Scorsese, he is considered to be one of the most influential actors of his generation.", birth: new Date("1943-08-17")},{name: "Robert Duvall", bio: "Robert Selden Duvall is an American actor and filmmaker. With a career spanning seven decades, he is regarded as one of the greatest actors of all time. He is the recipient of an Academy Award, four Golden Globe Awards, a BAFTA Award, two Primetime Emmy Awards, and a Screen Actors Guild Award.", birth: new Date("1931-01-05")}] , imagePath: "thegodfatherpartii.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "12 Angry Men", description: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Sidney Lumet", bio: "Sidney Arthur Lumet was an American film director. Lumet started his career in theatre before transitioning to film where he gained a reputation for making realistic and gritty New York dramas which focused on the working class, tackled social injustices and often questioned authority.", birth: new Date("1924-06-25"), death: new Date("2011-04-09") }, actors: [{ name: "Henry Fonda", bio: "Henry Jaynes Fonda was an American actor whose career spanned five decades on Broadway and in Hollywood. On screen and stage, he often portrayed characters that embodied an everyman image. Born and raised in Nebraska, Fonda made his mark early as a Broadway actor and made his Hollywood film debut in 1935.", birth: new Date("1905-05-16"), death: new Date("1962-08-12")},{ name: "Lee J. Cobb", bio: "Lee J. Cobb was an American actor, known both for film roles and his work on the Broadway stage, as well as for his television role as the star of the TV series The Virginian. He often played arrogant, intimidating and abrasive characters, but he also acted as respectable figures such as judges and police officers.", birth: new Date("1911-12-08"), death: new Date("1976-02-11")},{name: "Martin Balsam", bio: "Martin Henry Balsam was an American actor. He had a prolific career in character roles in film, in theatre, and on television.", birth: new Date("1919-11-04"), death: new Date("1996-02-13")}] , imagePath: "12angrymen.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "Schindler's List", description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Steven Spielberg", bio: "Steven Allan Spielberg is an American film director, producer and screenwriter. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director in history.", birth: "1946-12-18" }, actors: [{ name: "Liam Neeson", bio: "William John Neeson OBE is an actor from Northern Ireland. He has received several accolades, including nominations for an Academy Award, a BAFTA Award, three Golden Globe Awards, and two Tony Awards. In 2020, he was placed seventh on The Irish Times list of Ireland's 50 Greatest Film Actors.", birth: new Date("1952-06-07")},{ name: "Ralph Fiennes", bio: "Ralph Nathaniel Twisleton-Wykeham-Fiennes is an English actor, film producer, and director. A Shakespeare interpreter, he excelled onstage at the Royal National Theatre before having further success at the Royal Shakespeare Company.", birth: new Date("1962-12-22")}, {name: "Ben Kingsley", bio: "Sir Ben Kingsley is an English actor. He has received various accolades throughout his career spanning five decades, including an Academy Award, a British Academy Film Award, a Grammy Award, and two Golden Globe Awards. Kingsley was appointed Knight Bachelor in 2002 for services to the British film industry.", birth: new Date("1943-12-31")}] , imagePath: "schindlerslin.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "The Lord of the Rings: The Return of the King", description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", genre: { name: "Adventure", description: "The adventure genre is so similar to the action genre that the billing for adventure films is sometimes action/adventure movies. Films in the adventure genre usually contain the same basic genre elements as an action movie, with the setting as the critical difference. Adventure movies are typically set in an exotic, far away, or unfamiliar locale. This category can include swashbuckler films and survival films." }, director: {name: "Peter Jackson", bio: "Sir Peter Robert Jackson ONZ KNZM is a New Zealand film director, screenwriter and producer. He is best known as the director, writer and producer of the Lord of the Rings trilogy and the Hobbit trilogy, both of which are adapted from the novels of the same name by J. R. R. Tolkien.", birth: new Date("1961-10-31") }, actors: [{name: "Elijah Wood", bio: "Elijah Jordan Wood is an American actor and producer. He is best known for his portrayal of Frodo Baggins in The Lord of the Rings film trilogy and The Hobbit: An Unexpected Journey. Wood made his film debut with a small part in Back to the Future Part II.", birth: new Date("1981-01-28") },{name: "Viggo Mortensen", bio: "Viggo Peter Mortensen Jr. R is an American actor. He made his film debut in a small role in Peter Weir's 1985 thriller Witness. He appeared in several notable films, including The Indian Runner, Carlito's Way, Crimson Tide, Daylight, The Portrait of a Lady, G.I. Jane, A Perfect Murder, A Walk on the Moon, and 28 Days.", birth: new Date("1958-10-20") },{name: "Ian Mckellen", bio: "Sir Ian Murray McKellen CH CBE is an English actor. With a career spanning more than six decades, he is noted for his roles on the screen and stage in genres ranging from Shakespearean dramas and modern theatre to popular fantasy and science fiction.", birth: new Date("1939-05-25")}] , imagePath: "tlorthereturnoftheking.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "Pulp Fiction", description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Quentin Tarantino", bio: "Quentin Jerome Tarantino is an American film director, screenwriter, producer, actor, and author. His films are characterized by stylized violence, extended dialogue including a pervasive use of profanity, and references to popular culture.", birth: new Date("1963-03-27") }, actors: [{ name: "John Travolta", bio: "John Joseph Travolta is an American actor. He became prominent during the 1970s, appearing on the television sitcom Welcome Back, Kotter and starring in the box office successes Carrie, Saturday Night Fever, Grease, and Urban Cowboy.", birth: new Date("1954-02-18")},{ name: "Samuel L. Jackson", bio: "Samuel Leroy Jackson is an American actor. One of the most widely recognized actors of his generation, the films in which he has appeared have collectively grossed over $27 billion worldwide, making him the second-highest-grossing actor of all time.", birth: new Date("1948-12-21")},{name: "Uma Thurman", bio: "Uma Karuna Thurman is an American actress and former model. She has performed in a variety of films, from romantic comedies and dramas to science fiction and action films. Following her appearances on the December 1985 and May 1986 covers of British Vogue, Thurman starred in Dangerous Liaisons.", birth: new Date("1970-04-29")}] , imagePath: "pulpfiction.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "The Lord of the Rings: The Fellowship of the Ring", description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", genre: { name: "Adventure", description: "The adventure genre is so similar to the action genre that the billing for adventure films is sometimes action/adventure movies. Films in the adventure genre usually contain the same basic genre elements as an action movie, with the setting as the critical difference. Adventure movies are typically set in an exotic, far away, or unfamiliar locale. This category can include swashbuckler films and survival films." }, director: {name: "Peter Jackson", bio: "Sir Peter Robert Jackson ONZ KNZM is a New Zealand film director, screenwriter and producer. He is best known as the director, writer and producer of the Lord of the Rings trilogy and the Hobbit trilogy, both of which are adapted from the novels of the same name by J. R. R. Tolkien.", birth: new Date("1961-10-31") }, actors: [{name: "Elijah Wood", bio: "Elijah Jordan Wood is an American actor and producer. He is best known for his portrayal of Frodo Baggins in The Lord of the Rings film trilogy and The Hobbit: An Unexpected Journey. Wood made his film debut with a small part in Back to the Future Part II.", birth: new Date("1981-01-28") },{name: "Ian Mckellen", bio: "Sir Ian Murray McKellen CH CBE is an English actor. With a career spanning more than six decades, he is noted for his roles on the screen and stage in genres ranging from Shakespearean dramas and modern theatre to popular fantasy and science fiction.", birth: new Date("1939-05-25")},{ name: "Orlando Bloom", bio: "Orlando Jonathan Blanchard Copeland Bloom is an English actor. He made his breakthrough as the character Legolas in The Lord of the Rings film series. He reprised his role in The Hobbit film series.", birth: new Date("1977-02-13")}] , imagePath: "tlorthefellowshipofthering.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "The Good, the Bad and the Ugly", description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.", genre: { name: "Western", description: "Westerns tell the tale of a cowboy or gunslinger pursuing an outlaw in the Wild West. The main character often seeks revenge and will face the criminal in a duel or shootout at the end. Westerns are vivid productions set in the American West—such as the desert, mountains, or plains—that can inspire and inform the characters and the action. Spaghetti westerns, space westerns, and sci-fi westerns are all subgenres within the Western category." }, director: {name: "Sergio Leone", bio: "Sergio Leone was an Italian film director, producer, and screenwriter, credited as the pioneer of the Spaghetti Western genre. He is widely regarded as one of the most influential directors in the history of cinema. Leone's film-making style includes juxtaposing extreme close-up shots with lengthy long shots. ", birth: new Date("1929-01-03"), death: new Date("1989-04-30"), }, actors: [{name: "Clint Eastwood", bio: "Clinton Eastwood Jr. is an American actor and film director. After achieving success in the Western TV series Rawhide, Eastwood rose to international fame with his role as the \"Man with No Name\" in Sergio Leone's \"Dollars Trilogy\" of Spaghetti Westerns during the mid-1960s and as antihero cop Harry Callahan in the five Dirty Harry films throughout the 1970s and 1980s.", birth: new Date("1930-05--31")},{name: "Eli Wallach", bio: "Eli Herschel Wallach was an American film, television, and stage actor from New York City. Known for his character actor roles, his entertainment career spanned over six decades. He received a BAFTA Award, a Tony Award and an Emmy Award.", birth: new Date("1915-12-07"), death: new Date("2014-06-24")},{name: "Lee Van Cleef", bio: "Clarence LeRoy Van Cleef Jr. was an American actor. He appeared in over 170 film and television roles in a career spanning nearly 40 years, but is best known as a star of Italian Spaghetti Westerns, particularly the Sergio Leone-directed Dollars Trilogy films For a Few Dollars More and The Good, the Bad and the Ugly.", birth: new Date("1925-01-09"), death: new Date("1985-12-16")}] , imagePath: "thegoodthebadandtheugly.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "Forest Gump", description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "Robert Zemeckis", bio: "Robert Lee Zemeckis is an American filmmaker. He first came to public attention as the director of the action-adventure romantic comedy Romancing the Stone, the science-fiction comedy Back to the Future film trilogy, and the live-action/animated comedy Who Framed Roger Rabbit.", birth: new Date("1952-05-14")}, actors: [{ name: "Tom Hanks", bio: "Thomas Jeffrey Hanks is an American actor and filmmaker. Known for both his comedic and dramatic roles, he is one of the most popular and recognizable film stars worldwide, and is regarded as an American cultural icon.", birth: new Date("1956-07-09")},{name: "Robin Wright", bio: "Robin Gayle Wright is an American actress and director. She has received various accolades, including a Golden Globe Award, and nominations for eight Primetime Emmy Awards. Wright first gained attention for her role as Kelly Capwell in the NBC Daytime soap opera Santa Barbara from 1984 to 1988.", birth: new Date("1966-04-08") },{name: "Gary Sinise", bio: "Gary Alan Sinise is an American actor. Among other awards, he has won a Primetime Emmy Award, a Golden Globe Award, a Tony Award, and four Screen Actors Guild Awards. He has also received a star on the Hollywood Walk of Fame, and was nominated for an Academy Award.", birth: new Date("1955-03-17")}] , imagePath: "forestgump.png", featured: true }; db.movies.insertOne(movie1);
var movie1 = { title: "Fight Club", description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", genre: { name: "Drama", description: "The drama genre features stories with high stakes and many conflicts. They’re plot-driven and demand that every character and scene move the story forward. Dramas follow a clearly defined narrative plot structure, portraying real-life scenarios or extreme situations with emotionally-driven characters. Films that fall into drama sub-genres include historical drama or costume drama, romantic drama, teen drama, medical drama, docudrama, film noir, and neo-noir." }, director: {name: "David Fincher", bio: "David Andrew Leo Fincher is an American filmmaker. His films, most of which are psychological thrillers, have collectively grossed over $2.1 billion worldwide and have received 40 Academy Award nominations; this includes three Best Director nominations for him.", birth: new Date("1962-08-28")}, actors: [{ name: "Brad Pitt", bio: "William Bradley Pitt is an American actor and film producer. He is the recipient of various accolades, including two Academy Awards, two British Academy Film Awards, two Golden Globe Awards, and a Primetime Emmy Award.", birth: new Date("1963-12-18")},{ name: "Edward Norton", bio: "Edward Harrison Norton is an American actor. Norton was drawn to theatrical productions at local venues as a child. After graduating from Yale College in 1991, he worked for a few months in Japan before moving to Manhattan to pursue an acting career.", birth: new Date("1969-08-18")},{name: "Meat Loaf", bio: "Michael Lee Aday, known professionally as Meat Loaf, was an American rock singer and actor known for his powerful, wide-ranging voice and theatrical live shows. He is on the list of bestselling music artists.", birth: new Date("1947-09-27"), death: new Date("2022-01-20")}] , imagePath: "fightclub.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "The Lord of the Rings: The Two Towers", description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", genre: { name: "Adventure", description: "The adventure genre is so similar to the action genre that the billing for adventure films is sometimes action/adventure movies. Films in the adventure genre usually contain the same basic genre elements as an action movie, with the setting as the critical difference. Adventure movies are typically set in an exotic, far away, or unfamiliar locale. This category can include swashbuckler films and survival films." }, director: {name: "Peter Jackson", bio: "Sir Peter Robert Jackson ONZ KNZM is a New Zealand film director, screenwriter and producer. He is best known as the director, writer and producer of the Lord of the Rings trilogy and the Hobbit trilogy, both of which are adapted from the novels of the same name by J. R. R. Tolkien.", birth: new Date("1961-10-31") }, actors: [{name: "Elijah Wood", bio: "Elijah Jordan Wood is an American actor and producer. He is best known for his portrayal of Frodo Baggins in The Lord of the Rings film trilogy and The Hobbit: An Unexpected Journey. Wood made his film debut with a small part in Back to the Future Part II.", birth: new Date("1981-01-28") },{name: "Viggo Mortensen", bio: "Viggo Peter Mortensen Jr. R is an American actor. He made his film debut in a small role in Peter Weir's 1985 thriller Witness. He appeared in several notable films, including The Indian Runner, Carlito's Way, Crimson Tide, Daylight, The Portrait of a Lady, G.I. Jane, A Perfect Murder, A Walk on the Moon, and 28 Days.", birth: new Date("1958-10-20") },{name: "Ian Mckellen", bio: "Sir Ian Murray McKellen CH CBE is an English actor. With a career spanning more than six decades, he is noted for his roles on the screen and stage in genres ranging from Shakespearean dramas and modern theatre to popular fantasy and science fiction.", birth: new Date("1939-05-25")}] , imagePath: "tlorthetwotowers.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "Inception", description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.", genre: { name: "Science Fiction", description: "The sci-fi genre builds worlds and alternate realities filled with imagined elements that don’t exist in the real world. Science fiction spans a wide range of themes that often explore time travel, space travel, are set in the future, and deal with the consequences of technological and scientific advances. Sci-fi movies typically involve meticulous world-building with strong attention to detail for the audience to believe the story and universe." }, director: {name: "Chrisopher Nolan", bio: "Christopher Edward Nolan CBE is a British and American filmmaker. Known for his Hollywood blockbusters with complex storytelling, Nolan is considered a leading filmmaker of the 21st century. His films have grossed $5 billion worldwide.", birth: new Date("1970-07-30") }, actors: [{ name: "Leonardo DiCaprio", bio: "Leonardo Wilhelm DiCaprio is an American actor and film producer. Known for his work in biographical and period films, he is the recipient of numerous accolades, including an Academy Award, a British Academy Film Award and three Golden Globe Awards.", birth: new Date("1974-11-11")},{ name: "Joseph Gordon-Levitt", bio: "Joseph Leonard Gordon-Levitt is an American actor. He has received various accolades, including nominations for the Golden Globe Award for Best Actor – Motion Picture Musical or Comedy for his leading performances in 500 Days of Summer and 50/50.", birth: new Date("1981-02-17")},{name: "Elliot Page", bio: "Elliot Page is a Canadian actor. He has received various accolades, including nominations for an Academy Award, two BAFTA Awards and a Primetime Emmy Award. Page was assigned female at birth, and later publicly came out as a trans man in December 2020.", birth: "1987-02-21"}] , imagePath: "inception.png", featured: false }; db.movies.insertOne(movie1);
var movie1 = { title: "Star Wars: Episode V - The Empire Strikes Back", description: "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.", genre: { name: "Fantasy", description: "Films in the fantasy genre feature magical and supernatural elements that do not exist in the real world. Although some films juxtapose a real-world setting with fantastical elements, many create entirely imaginary universes with their own laws, logic, and populations of imaginary races and creatures. Like science fiction films, fantasy films are speculative but unrelated to reality or scientific fact. High fantasy, fairy tales, and magical realism are all fantasy subgenres." }, director: {name: "Irvin Kershner", bio: "Irvin Kershner was an American film director, actor, and producer of film and television. He gained notice early in his career as a filmmaker for directing quirky, independent drama films, while working as an influential lecturer at the University of Southern California.", birth: new Date("1923-04-29"), death: new Date("2010-11-27"), }, actors: [{name: "Mark Hamill", bio: "Mark Richard Hamill is an American actor, voice artist, and writer. He is most widely known for his role as Luke Skywalker in the Star Wars franchise, beginning with the original 1977 film and subsequently winning three Saturn Awards for his performances in The Empire Strikes Back (1980), Return of the Jedi (1983), and The Last Jedi (2017). His other film appearances include Corvette Summer (1978) and The Big Red One (1980). He also appeared in several theater productions during the 1980s.", birth: new Date("1951-09-25") },{name: "Harrison Ford", bio: "Harrison Ford is an American actor. He has been a leading man in films of several genres and is regarded as an American cultural icon. His films have grossed more than $5.4 billion in North America and more than $9.3 billion worldwide, making him the seventh-highest-grossing actor in North America.", birth: new Date("1942-07-13")},{name: "Carrie Fisher", bio: "Carrie Frances Fisher was an American actress and writer. She was best known for playing Princess Leia in the original Star Wars films.", birth: new Date("1956-10-21"), death: new Date("2016-12-27")}], imagePath: "starwarsepisodev.png", featured: false}; db.movies.insertOne(movie1);
var movie1 = { title: "Star Wars: Episode IV - A New Hope", description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", genre: { name: "Fantasy", description: "Films in the fantasy genre feature magical and supernatural elements that do not exist in the real world. Although some films juxtapose a real-world setting with fantastical elements, many create entirely imaginary universes with their own laws, logic, and populations of imaginary races and creatures. Like science fiction films, fantasy films are speculative but unrelated to reality or scientific fact. High fantasy, fairy tales, and magical realism are all fantasy subgenres." }, director: {name: "George Lucas", bio: "George Walton Lucas Jr. is an American filmmaker. Lucas is best known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts, Industrial Light & Magic, and THX. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.", birth: new Date("1944-05-14") }, actors: [{name: "Mark Hamill", bio: "Mark Richard Hamill is an American actor, voice artist, and writer. He is most widely known for his role as Luke Skywalker in the Star Wars franchise, beginning with the original 1977 film and subsequently winning three Saturn Awards for his performances in The Empire Strikes Back (1980), Return of the Jedi (1983), and The Last Jedi (2017). His other film appearances include Corvette Summer (1978) and The Big Red One (1980). He also appeared in several theater productions during the 1980s.", birth: new Date("1951-09-25") },{name: "Harrison Ford", bio: "Harrison Ford is an American actor. He has been a leading man in films of several genres and is regarded as an American cultural icon. His films have grossed more than $5.4 billion in North America and more than $9.3 billion worldwide, making him the seventh-highest-grossing actor in North America.", birth: new Date("1942-07-13")},{name: "Carrie Fisher", bio: "Carrie Frances Fisher was an American actress and writer. She was best known for playing Princess Leia in the original Star Wars films.", birth: new Date("1956-10-21"), death: new Date("2016-12-27")}], imagePath: "starwarsepisodeiv.png", featured: false}; db.movies.insertOne(movie1);

var user1 = {username: "dcrichlow1985",password: "abc1234!",first_name: "David",last_name: "Crichlow",email: "dcrichlow@davidcrichlow.com",birth: new Date("1985-12-19"),favorites: [ObjectId("6510c180c3067b746ee3603c"),ObjectId("6510bf95c3067b746ee3603a"),ObjectId("6510c558c3067b746ee3603f")]}; db.users.insertOne(user1);
var user1 = {username: "PParker1234",password: "abc1234!",first_name: "John",last_name: "Doe",email: "JDoe1234@gmail.com",birth: new Date(""),favorites: [ObjectId("6510be55c3067b746ee36039")]}; db.users.insertOne(user1);
var user1 = {username: "JDoe1234",password: "abc1234!",first_name: "Peter",last_name: "Parker",email: "PParker@avengers.com",birth: new Date("1991-12-20"),favorites: [ObjectId("6510c4b5c3067b746ee3603e"),ObjectId("6510c558c3067b746ee3603f")]}; db.users.insertOne(user1);
var user1 = {username: "thestrongestavenger01",password: "ironman2023",first_name: "Tony",last_name: "Stark",email: "iamironman@gmail.com",birth: new Date("1979-07-18"),favorites: [ObjectId("6510baddc3067b746ee36037"),ObjectId("6510b477c3067b746ee36033")]}; db.users.insertOne(user1);
var user1 = {username: "HulkMad",password: "argh01",first_name: "Bruce",last_name: "Banner",email: "bbanner@brucebanner.com",birth: new Date("08-19-1987"),favorites: []}; db.users.insertOne(user1);
var user1 = {username: "",password: "abc1234!",first_name: "",last_name: "",email: "",birth: new Date(""),favorites: []}; db.movies.insertOne(user1);
var user1 = {username: "",password: "abc1234!",first_name: "",last_name: "",email: "",birth: new Date(""),favorites: []}; db.movies.insertOne(user1);
var user1 = {username: "",password: "abc1234!",first_name: "",last_name: "",email: "",birth: new Date(""),favorites: []}; db.movies.insertOne(user1);
var user1 = {username: "",password: "abc1234!",first_name: "",last_name: "",email: "",birth: new Date(""),favorites: []}; db.movies.insertOne(user1);



app.post('/movies', async (req, res) => {
    await Movies.findOne({ username: req.body.title })
        .then((movie) => {
            if (movie) {
                return res.status(400).send(req.body.title + ' already exists');
            } else {
                Movies.create(
                {
                    title: req.body.title,
                    description: req.body.description,
                    genre: {
                        username: req.body.genre.username,
                        description: req.body.genre.description
                    },
                    director: {
                        name: req.body.director.Name,
                        bio: req.body.director.bio,
                        birth: req.body.director.birth,
                        death: req.body.director.death
                    },
                    actors: [
                        {
                            name: req.body.actors.name1,
                            bio: req.body.actors.bio1,
                            birth: req.body.actors.birth1,
                            death: req.body.actors.death1
                        },
                        {
                            name: req.body.actors.name2,
                            bio: req.body.actors.bio2,
                            birth: req.body.actors.birth2,
                            death: req.body.actors.death2
                        },
                        {
                            name: req.body.actors.name3,
                            bio: req.body.actors.bio3,
                            birth: req.body.actors.birth3,
                            death: req.body.actors.death3
                        },
                    ],
                    imagePath: req.body.imagePath,
                    featured: req.body.featured
                })
                .then((user) => { res.status(201).json(user) })
                .catch((err) => {
                    console.error(err);
                    res.status(500).send('Error: ' + err);
                })
            }
        })
        .catch((err) => {
            console.error(err);
            res.status(500).send('Error: ' + err);
        });
});